title: Frank Xu, Ph.D. Associate Professor
description: Director of the MS in Forensic Sciences: Cyber Investigations program (Baltimore Campus), University of Baltimore
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
