title: Dr. Frank Xu, Associate Professor, Director of the MS in Forensic Sciences: Cyber Investigations program
description: University of Baltimore, Frank Xu
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
